version: "3.0"
services:
  mentions_comments:
    image: vitosamson/submentions
    environment:
      DB_PATH: /mentions/mentions.db
    volumes:
      - /home/vito/projects/submentions:/mentions

  mentions_submissions:
    image: vitosamson/submentions
    environment:
      DB_PATH: /mentions/mentions.db
      TYPE: submissions
    volumes:
      - /home/vito/projects/submentions:/mentions
