version: "3.0"
services:
  mentions_comments:
    image: vitosamson/submentions:pi
    environment:
      DB_PATH: /mentions/mentions.db
    volumes:
      - /home/vito/projects/submentions:/mentions
      - /home/vito/projects/submentions/credentials.json:/app/credentials.json

  mentions_submissions:
    image: vitosamson/submentions:pi
    environment:
      DB_PATH: /mentions/mentions.db
      TYPE: submissions
    volumes:
      - /home/vito/projects/submentions:/mentions
      - /home/vito/projects/submentions/credentials.json:/app/credentials.json
